version: '3.8'

services:
  reverseproxy:
    container_name: reverseproxy
    image: mironouz/remote-school:nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html

  backend:
    container_name: backend
    image: mironouz/remote-school:api
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'

  frontend:
    container_name: frontend
    image: mironouz/remote-school:react
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - reverseproxy
    command: certonly --webroot --webroot-path=/var/www/html --email mironouz@gmail.com --agree-tos --no-eff-email --force-renewal -d mironouz.xyz

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge